"""
Meteor Madness AI tools.

These are controlled read-only tools for the AI analyst.
The AI can inspect simulation/environment data, but it does not
replace the physics engine or invent authoritative values.
"""

from __future__ import annotations

from typing import Any


def get_simulation_summary(context: dict[str, Any]) -> dict[str, Any]:
    """Return the current simulation state."""
    simulation = context.get("simulation") or {}
    asteroid = context.get("asteroid") or {}
    environment = context.get("environment") or {}
    impact_branch = context.get("impact_branch") or {}
    place = context.get("place") or {}

    return {
        "asteroid": asteroid,
        "simulation": simulation,
        "environment": environment,
        "impact_branch": impact_branch,
        "place": place,
        "coordinates": {
            "latitude": context.get("latitude"),
            "longitude": context.get("longitude"),
            "entry_azimuth_deg": context.get("entry_azimuth_deg"),
        },
    }


def get_impact_data(context: dict[str, Any]) -> dict[str, Any]:
    """Return impact-specific values."""
    simulation = context.get("simulation") or {}
    branch = context.get("impact_branch") or {}
    place = context.get("place") or {}

    return {
        "impact_energy_J": simulation.get("impact_energy_J"),
        "impact_energy_megatons_tnt": simulation.get(
            "impact_energy_megatons_tnt"
        ),
        "outcome": simulation.get("outcome"),
        "fragmentation_detected": simulation.get(
            "fragmentation_detected"
        ),
        "fragmentation_altitude_m": simulation.get(
            "fragmentation_altitude_m"
        ),
        "branch": branch,
        "place": place,
        "coordinates": {
            "latitude": context.get("latitude"),
            "longitude": context.get("longitude"),
        },
    }


def get_environment_data(context: dict[str, Any]) -> dict[str, Any]:
    """
    Return GEBCO/environment information plus the resolved
    human-readable impact location.

    The place information comes from the backend reverse-geocoder.
    Gemini must use this value rather than guessing a location
    from latitude/longitude.
    """
    environment = context.get("environment") or {}
    place = context.get("place") or {}

    coordinates = (
        environment.get("coordinates")
        or {}
    )

    latitude = context.get("latitude")
    longitude = context.get("longitude")

    if latitude is None:
        latitude = coordinates.get("latitude")

    if longitude is None:
        longitude = coordinates.get("longitude")

    return {
        "surface": (
            context.get("surface")
            or environment.get("surface")
            or "unknown"
        ),
        "surface_confidence": (
            context.get("surface_confidence")
            or environment.get("surface_confidence")
            or environment.get("confidence")
        ),
        "terrain_source": (
            environment.get("terrain_source")
            or environment.get("source")
        ),
        "data_status": environment.get("data_status"),
        "elevation_m": environment.get("elevation_m"),
        "bathymetry_m": environment.get("bathymetry_m"),
        "material": environment.get("material"),

        # Human-readable geographic identification.
        "place": {
            "display_name": place.get("display_name"),
            "short_name": place.get("short_name"),
            "city": place.get("city"),
            "state": place.get("state"),
            "country": place.get("country"),
            "source": place.get("source"),
        },

        "coordinates": {
            "latitude": latitude,
            "longitude": longitude,
        },
    }


def get_consequences_data(context: dict[str, Any]) -> dict[str, Any]:
    """Return consequences generated by the current simulation."""
    branch = context.get("impact_branch") or {}
    place = context.get("place") or {}

    return {
        "branch": branch.get("branch"),
        "models_run": branch.get("models_run"),
        "crater": branch.get("crater"),
        "blast": branch.get("blast"),
        "thermal": branch.get("thermal"),
        "tsunami": branch.get("tsunami"),
        "seismic": branch.get("seismic"),
        "place": place,
    }


def get_planetary_defence_context() -> dict[str, Any]:
    """
    Educational planetary-defence reference.

    This describes broad scientific concepts only.
    It is not an operational mission planner.
    """
    return {
        "kinetic_impactor": {
            "description": (
                "A spacecraft impacts an asteroid to change its velocity "
                "slightly, potentially changing its future trajectory."
            ),
            "important_variables": [
                "warning time",
                "asteroid mass",
                "asteroid composition",
                "impact geometry",
                "required deflection",
            ],
        },
        "gravity_tractor": {
            "description": (
                "A spacecraft uses mutual gravitational attraction to "
                "gradually alter an asteroid's trajectory."
            ),
            "important_variables": [
                "warning time",
                "asteroid mass",
                "spacecraft mass",
                "station-keeping duration",
            ],
        },
        "nuclear_deflection": {
            "description": (
                "A nuclear device is sometimes discussed as a planetary-"
                "defence option for extreme scenarios. Outcomes depend on "
                "asteroid properties, geometry and warning time."
            ),
            "important_variables": [
                "warning time",
                "asteroid structure",
                "trajectory",
                "required deflection",
            ],
        },
        "laser_ablation": {
            "description": (
                "Directed energy could theoretically heat an asteroid's "
                "surface and produce material ejection, creating a small "
                "propulsive effect over time."
            ),
            "important_variables": [
                "warning time",
                "surface properties",
                "energy delivery",
                "asteroid rotation",
            ],
        },
        "reconnaissance": {
            "description": (
                "Improved observation reduces uncertainty in orbit and "
                "physical properties and informs later mitigation decisions."
            ),
            "important_variables": [
                "orbit uncertainty",
                "size",
                "composition",
                "rotation",
                "shape",
            ],
        },
        "civil_defence": {
            "description": (
                "If deflection is unavailable or insufficient, emergency "
                "planning can reduce human exposure to predicted effects."
            ),
            "important_variables": [
                "impact probability",
                "impact location",
                "population exposure",
                "warning time",
                "infrastructure vulnerability",
            ],
        },
    }
